"""ADDED NECESSARY TABLES 

Revision ID: 68cf328c208e
Revises: 1fdd92301509
Create Date: 2022-07-20 00:48:03.212427

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c5b35619743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('users',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    #op.drop_table('post')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('posts')
    op.drop_table('users')
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('post',
    #sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    #sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    #sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    #sa.PrimaryKeyConstraint('id', name='post_pkey')
    #)
    #op.drop_table('users')
    #op.drop_table('posts')
    # ### end Alembic commands ###
