"""ADDED NECESSARY TABLES

Revision ID: 6260580c89c4
Revises: 2c5b35619743
Create Date: 2022-07-20 15:28:10.196869

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6260580c89c4'
down_revision = '2c5b35619743'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
 
def downgrade() -> None:
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###